image: Visual Studio 2019

# Download script file from GitHub
init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - git submodule update --init --recursive
  - ps: choco install pandoc --no-progress
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"

environment:
  app_version: "2.2"
  USE_RTOOLS: true
  NOT_CRAN: true
  KEEP_VIGNETTES: true
  _R_CHECK_FORCE_SUGGESTS_: false
  R_ARCH: x64
  R_VERSION: "4.3.1"
  R_CHECK_ARGS: --no-build-vignettes --no-manual --as-cran

version: "$(app_version).{build}"

before_build:
  - rake "prepare_for_build[%APPVEYOR_BUILD_VERSION%]"

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install curl
  - Rscript .github/workflows/install_dependencies.R

on_success:
  - Rscript -e "spelling::spell_check_package()"

test_script:
  - travis-tool.sh run_tests

after_test:
  - ps: copy ospsuite.reportingengine_*.zip ospsuite.reportingengine.zip
  - ps: copy ospsuite.reportingengine_*.tar.gz ospsuite.reportingengine.tar.gz

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*.tar.gz'
    name: Bits

  - path: '\*.zip'
    name: Bits

platform: x64

skip_commits:
  files:
    - "*.md"
    - .github/workflows/*.yml
    - .github/workflows/*.sh
    - .github/workflows/Dockerfile
    - .github/workflows/*.R
    - '_pkgdown.yml'

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
    - develop

pull_requests:
  do_not_increment_build_number: true
