image: Visual Studio 2019

# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

#cache:
#  - C:\RLibrary

environment:
  USE_RTOOLS: true
  NOT_CRAN: true
  # env vars that may need to be set, at least temporarily, from time to time
  # see https://github.com/krlmlr/r-appveyor#readme for details
  # R_REMOTES_STANDALONE: true
  R_ARCH: x64
  COVERALLS_TOKEN:
    secure: Qo8To6hV3C2ghrS0Z+pPyvaBaEpE24Pwr7LF8AbiMO9HL+pkwX1U3kYGUNzJF5EU

# Adapt as necessary starting from here

build_script:
  - Rscript -e "update.packages(repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('devtools', repos = 'http://cran.us.r-project.org', lib = 'C:/RLibrary', type='binary')"
  - Rscript -e "install.packages('./tools/rClr_0.8.3.zip', repos = NULL, type = 'binary', lib = 'C:/RLibrary')"
  - Rscript -e "devtools::install_github('Open-Systems-Pharmacology/TLF-Library', ref ='develop', lib = 'C:/RLibrary')"
  - Rscript -e "devtools::install_github('Open-Systems-Pharmacology/OSPSuite-R', ref ='develop', lib = 'C:/RLibrary')"
  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install curl
  - Rscript -e "install.packages('covr', repos = 'http://cran.us.r-project.org', lib = 'C:/RLibrary')"

on_success:
  - Rscript -e "covr::codecov(function_exclusions = c('print.*', '\\.onLoad'))"

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

platform: x64

skip_commits:
  files:
    - "*.md"

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
    - develop

pull_requests:
  do_not_increment_build_number: true

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyFEAs8X080yIO8g1FLt3tNfBN4OpeBnkgrXzf7AqNKV5561x7Coux3ByGrHmsL1sCo=
