# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: Run Nightly Code Coverage
# schedule from https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
on: push
jobs:
  test-coverage:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      # Install ospsuite ecosystem from Github 
      # r-lib/actions/setup-r-dependencies@v2 install even suggested packages, tracelib included
      # enforce not installing tracelib
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            github::Open-Systems-Pharmacology/OSPSuite.RUtils@develop
            github::Open-Systems-Pharmacology/TLF-Library@develop
            github::Open-Systems-Pharmacology/OSPSuite-R@develop
            tracelib=?ignore
          needs: coverage
      - name: Test coverage
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
          )
        shell: Rscript {0}
      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
