install.packages(c('dplyr','purrr','covr','readr','tidyr','webshot','spelling','readxl','data.table','gridtext','ggtext','tidyselect','testthat','rmarkdown','pkgdown','openxlsx'), repos = 'http://cran.us.r-project.org', type='win.binary')
download.file('https://github.com/Open-Systems-Pharmacology/rSharp/releases/download/v1.0.0/rSharp-v1.0.0-Windows-r_4.4.0.zip', destfile = "rsharp.zip", mode = "wb")
download.file('https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/releases/download/v1.5.30/ospsuite.utils_1.5.30.zip', destfile = "ospsuite-utils.zip", mode = "wb")
download.file('https://github.com/Open-Systems-Pharmacology/TLF-Library/releases/download/v1.5.158/tlf_1.5.158.zip', destfile = "tlf.zip", mode = "wb")
download.file('https://github.com/Open-Systems-Pharmacology/OSPSuite-R/releases/download/v12.1.0/ospsuite_12.1.0.zip', destfile = "ospsuite.zip", mode = "wb")
unzip("rsharp.zip")
unzip("ospsuite-utils.zip")
unzip("tlf.zip")
unzip("ospsuite.zip")
rSharp_archive <- list.files( pattern = "rSharp.*\\.zip")
ospsuiteUtils_archive <- list.files( pattern = "ospsuite-utils.*\\.zip")
tlf_archive <- list.files( pattern = "tlf.*\\.zip")
ospsuite_archive <- list.files( pattern = "ospsuite.*\\.zip")
install.packages(rSharp_archive, repos = NULL, type = "binary")
install.packages(ospsuiteUtils_archive, repos = NULL, type = "binary")
install.packages(tlf_archive, repos = NULL, type = "binary")
install.packages(ospsuite_archive, repos = NULL, type = "binary")
unlink("rsharp.zip")
unlink("ospsuite-utils.zip")
unlink("tlf.zip")
unlink("ospsuite.zip")
