# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: lint.yaml

permissions: write-all

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: austenstone/job-id@v1
        id: job-id

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.
          needs: lint

      - name: Lint
        run: |
          lintr::lint_package(
            linters=lintr::linters_with_defaults(
              object_name_linter = lintr::object_name_linter(
                styles = c("camelCase","CamelCase","symbols"), 
                regexes = c(na="na.rm", randomSeed=".Random.seed", tracelib="re.t", linuxCores="cfs_")
              ),
              line_length_linter = NULL, 
              object_length_linter = NULL, 
              brace_linter = NULL, 
              paren_body_linter = NULL, 
              trailing_whitespace_linter = NULL, 
              trailing_blank_lines_linter = NULL, 
              spaces_left_parentheses_linter = NULL, 
              infix_spaces_linter = NULL
            ),
            exclusions = list("tests/dev")
          )
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
          
      - name: Soft failing
        if: failure() # This runs when the previous step fails
        # Use the following recommendations
        # https://docs.github.com/fr/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos${{ github.owner }}/${{ github.repository }}/check-runs/${{ steps.job-id.outputs.job-id }} \
            -d '{"name":"lint","status":"completed","conclusion": "neutral"}'

