# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: lint.yaml

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.
          needs: lint

      - name: Lint
        run: |
          lintr::lint_package(
            linters=lintr::linters_with_defaults(
              object_name_linter = lintr::object_name_linter(
                styles = c("camelCase","CamelCase","symbols"), 
                regexes = c(na="na.rm", randomSeed=".Random.seed", tracelib="re.t", linuxCores="cfs_")
              ),
              line_length_linter = NULL, 
              object_length_linter = NULL, 
              brace_linter = NULL, 
              paren_body_linter = NULL, 
              trailing_whitespace_linter = NULL, 
              trailing_blank_lines_linter = NULL, 
              spaces_left_parentheses_linter = NULL, 
              infix_spaces_linter = NULL
            ),
            exclusions = list("tests/dev")
          )
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
