name: Run Reporting Engine Tests under Linux
on: 
  pull_request:
#  push:

jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
            r_version: [4.1.0] #[3.6.3, 4.1.0]
            os_version: [centos7] #[centos7, bionic]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/Dockerfile
          build-args: |
            r_version=${{ matrix.r_version }}
            os_version=${{ matrix.os_version }}
          push: false
          tags: |
            ghcr.io/open-systems-pharmacology/tests_ospsuite.reportingengine-r${{ matrix.r_version }}-${{ matrix.os_version }}:latest
