name: Main-Workflow

on:
  push:
    branches: [main]
  pull_request:

permissions: read-all
  
jobs:
  bump-dev-version: # only do that when actually merging in main/develop branch
    permissions: 
      contents: write
    if: github.event_name != 'pull_request'
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/bump_dev_version_tag_branch.yaml@main
    with:
      app-id: ${{ vars.VERSION_BUMPER_APPID }}
    secrets:
      private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

  R-CMD-Check:
    if: ${{ !cancelled() }}
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/R-CMD-check-build.yaml@main

  test-coverage:
    if: ${{ !cancelled() }}
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/test-coverage.yaml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  pkgdown:
    permissions: 
      contents: write
    if: ${{ !cancelled() }}
    uses:  Open-Systems-Pharmacology/Workflows/.github/workflows/pkgdown.yaml@main

